[tool.ruff]
line-length = 100
select = ["E","F","W","I"]
target-version = "py311"
exclude = ["venv",".venv","build","dist"]

[tool.isort]
profile = "black"
line_length = 100

[tool.bandit]
skips = ["B101"]

[tool.pytest.ini_options]
addopts = "--cov=app --cov-report=term-missing"
